const path = require('path');
const fs = require('fs');
const crypto = require('crypto');

/**
 * AUTOMATED LICENSE SYNC TOOL
 * This tool eliminates the "HWID Paradox" by pulling the EXACT string 
 * generated by the native module on the current machine and using it
 * to sign a valid, hardware-locked license.
 */

// 1. Get the actual HWID from the native module (Matches main.cjs reality)
const nativePath = path.resolve(__dirname, '../build/Release/recorder_detect.node');
if (!fs.existsSync(nativePath)) {
    console.error('Error: Native security module not found. Please run "npm run rebuild" first.');
    process.exit(1);
}

try {
    const recorderDetect = require(nativePath);
    const hwid = recorderDetect.getHardwareID();
    console.log('=========================================');
    console.log('🚀 SYSTEM HWID DETECTED:', hwid);
    console.log('=========================================');

    // 2. Load signing keys and master key
    const privateKey = fs.readFileSync('tools/private.pem', 'utf8');
    const masterKeyHex = fs.readFileSync('tools/master_key.txt', 'utf8').trim();
    const masterKey = Buffer.from(masterKeyHex, 'hex');

    // 3. Encrypt MasterKey with the REAL HWID (Self-Generating Sequence)
    // We use the same SHA256(HWID) + Zero IV logic found in main.cjs
    const cipher = crypto.createCipheriv('aes-256-cbc', 
        crypto.createHash('sha256').update(hwid).digest(), 
        Buffer.alloc(16, 0)
    );
    const encryptedMasterKey = Buffer.concat([cipher.update(masterKey), cipher.final()]);

    // 4. Generate the License Data Structure
    const licenseData = {
        license_id: `LIC-${Date.now().toString().slice(-6)}`,
        hardware_id: hwid,
        master_key: encryptedMasterKey.toString('base64'),
        min_app_version: "1.0.0",
        issued_at: new Date().toISOString().split('T')[0],
        expiry: "2027-01-01"
    };

    // 5. Canonicalize and Sign (RSA-2048)
    function canonicalStringify(obj) {
        if (typeof obj !== 'object' || obj === null) return JSON.stringify(obj);
        const sortedKeys = Object.keys(obj).sort();
        const result = {};
        sortedKeys.forEach(key => {
            result[key] = obj[key];
        });
        return JSON.stringify(result);
    }

    const dataString = canonicalStringify(licenseData);
    const signer = crypto.createSign('sha256');
    signer.update(dataString);
    signer.end();
    const signature = signer.sign(privateKey, 'base64');
    licenseData.signature = signature;

    // 6. Save directly to project root
    fs.writeFileSync('license.lic', JSON.stringify(licenseData, null, 2));
    console.log('✅ SUCCESS: license.lic generated and SYNCED for this system.');
    console.log('Location:', path.resolve('license.lic'));

} catch (e) {
    console.error('Fatal: Failed to synchronize license:', e.message);
    process.exit(1);
}
